###
GET http://localhost:4004/odata/v4/catalog/Books

###
POST http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

{
  "ID": "c99992",
  "title": "Test Book",
  "author": "Test Author",
  "price": 1
}

###
PATCH  http://localhost:4004/odata/v4/catalog/Books(ID = 'c99992')
Content-Type: application/json

{
  "title":  "Book Edited",
  "author": "Unknown Edited",
  "price": 500
}

###
POST http://localhost:4004/odata/v4/catalog/discount
Content-Type: application/json

{
  "bookID": "c12345"
}

###
POST http://localhost:4004/odata/v4/catalog/importBooks
Content-Type: application/json

{
  "isbn": "9780670858576"
}

###
GET http://localhost:4004/odata/v4/catalog/Books?$expand=author

###
POST http://localhost:4004/odata/v4/catalog/discount
Content-Type: application/json

{
  "bookID": "c12345"
}

###
POST http://localhost:4004/odata/v4/catalog/updateStock
Content-Type: application/json

{
    "bookID": "c12345",
    "quantity": 2
}

###
POST http://localhost:4004/odata/v4/catalog/restockBook
Content-Type: application/json

{
    "bookID": "58b8a415-de9c-45b8-a8a4-86a6555d5ec8",
    "quantity": 200
}

###
POST http://localhost:4004/odata/v4/catalog/reserveBook
Content-Type: application/json

{
    "bookID": "c12345",
    "quantity": 14
}

###
GET http://localhost:4004/odata/v4/catalog/Reservations?$expand=book($expand=author)

###
POST http://localhost:4004/odata/v4/catalog/cancelReservation
Content-Type: application/json

{
    "reservationID": "30768ca3-f53a-457f-9f4e-b2ef487e05ec"
}